### ISSUE TITLE
NullPointerException with null payload

### ISSUE THREAD

**Issue by jeff303** [CameraForensics/jest-for-appengine#1]
Hi, thanks for making this library.

I noticed an issue.  Line 57 of JestForAppEngineClient throws an NPE if the payload itself is null (ex: for GetTemplate).  That is, unless I'm using it incorrectly.  Sample code

```
        final GetTemplate getTemplate = new GetTemplate.Builder("my-template-id").build();
        JestResult res = client.execute(getTemplate);
```

**Comment by mattburns** [comment]
Sounds totally plausible, I only use a very small subset of the ES api with this project. If you have a proposed solution, I welcome pull requests :)

**Comment by ndtreviv** [comment]
Fixed!

**Comment by jeff303** [comment]
Thanks, this did indeed fix my issue.  For whatever reason, the zip file download from Github didn't have the updated jar, but I built it myself from the sources and that's working.  Thanks again.
